---
title: "arp_resource"
output: html_document
date: "2022-11-17"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, 
                      dev.args=list(bg="transparent"), fig.width=16,fig.height=12)
library(glptools)
glp_load_packages(TRUE)
library(arrow)
library(viridis)
library(forcats)
library(hrbrthemes)
library(glpdata)
```


```{r peer_citie}
FIPS_df <- glptools::FIPS_df

FIPS_info <- glptools::FIPS_info
```


```{r governments}
# Create clean governments data frame
projects <- read_csv("ARP Project Reports - Projects.csv",
                      col_types = "cccccccccccncnncnnccc")

## Read in city and county allocations
city_allocations <- read_csv("fiscalrecoveryfunds-metrocitiesfunding1-CSV.csv")
county_allocations <- read_csv("fiscalrecoveryfunds_countyfunding_2021.05.10-1a.csv")

# Select only government ID columns, keep only distinct rows, and replace the Birmingham FIPS code 1073 with 01073
governments <- projects %>%
  select(FIPS, 
         State, 
         city_county = `city/county`, 
         city_county_status = `city/county_status`) %>%
  distinct() %>%
  pull_peers()

# Should have 17 cities and 17 - 3 = 14 counties 

FIPS_population <- FIPS_info %>%
  filter(
    county != "St. Louis County", 
    FIPS != "MERGED", 
    current == 1)

# Read in city population data
city_pop <- read_csv("city_pop.csv")

FIPS_population %<>% 
  left_join(city_pop, by = "city") %>%
  select(FIPS, city, state, county, city_population = population)

# Read in county population and combine with city population
county_pop <- glpdata::population_county %>%
  filter(year == max(year),
         sex == "total",
         race == "total") %>%
  select(FIPS, county_population = population)

FIPS_population %<>%
  left_join(county_pop, by = "FIPS")

FIPS_population %<>%
  mutate(
    city = case_when(
      city == "Jacksonville" ~ "Jacksonville city",
      city == "Louisville" ~ "Louisville-Jefferson County",
      city == "St. Louis" ~ "St Louis",
      city == "Nashville" ~ "Nashville-Davidson",
      TRUE ~ city),
    county = case_when(
      county == "St. Louis City" ~ "St. Louis city", 
       county == "St. Louis County" ~ "St. Louis", 
      county == "Richmond City" ~ "Richmond city", 
      TRUE ~ county))

city_allocations %<>%
  inner_join(FIPS_population, by = c("State" = "state", "City" = "city")) %>%
  transmute(
    FIPS, 
    city_county_status = "city",
    allocation = Allocation) 

county_allocations %<>%
  mutate(
    County = str_remove_all(County, " County")) %>%
  inner_join(FIPS_population, by = c("State" = "state", "County" = "county")) %>%
  transmute(
    FIPS,
    city_county_status = "county",
    allocation = Allocation)

all_allocations <- bind_rows(city_allocations, county_allocations)

all_allocations %<>%
  mutate(allocation = str_remove(allocation, "\\$") %>% 
           str_remove_all(",") %>%
           as.numeric()) 

city_allocations <- all_allocations %>%
  filter(city_county_status == "city") %>%
  rename(city_allocation = allocation) %>%
  select(-city_county_status)

county_allocations <- all_allocations %>%
  filter(city_county_status == "county") %>%
  rename(county_allocation = allocation) %>%
  select(-city_county_status)

governments_wide <- FIPS_population %<>%
  left_join(city_allocations) %>%
  left_join(county_allocations) %>%
  select(FIPS, city_allocation, county_allocation, city_population, county_population) %>%
  mutate(total_allocation = city_allocation + county_allocation)

# Replace St. Louis FIPS since we have now added city and county data in the same row

governments_wide$FIPS[governments_wide$FIPS == "29510"] <- "MERGED"

all_allocations %<>%
  mutate(
    city_county_status = if_else(FIPS %in% c(18097, 21111, 47037), "merged", city_county_status)) %>%
  group_by(FIPS, city_county_status) %>%
  summarize(allocation = sum(allocation), .groups = "drop")


governments_long <- governments %>%
  left_join(all_allocations, by = c("FIPS", "city_county_status"))


rm(FIPS_population, governments, city_allocations, county_allocations, city_pop, county_pop, all_allocations)
```


```{r projects}
projects %<>%
  mutate(FIPS = if_else(FIPS == "1073", "01073", FIPS))


```

```{r louisville expenditures}
expenditures_lou <- read_csv("ARP Project Reports - Expenditures.csv",
                             col_types = "cccnnnnn")

```

```{r peer expenditure cleanup}

#create crosswalk file
expenditures_peer_crosswalk <- read_csv("ARP Project Reports - project_to_govenment_crosswalk.csv")


#read in quarterly expenditures
q4_2021_peer_exp <- read_csv("SLFRF-January-2022-Quarterly-Data-through-December-31-2021.xlsx - Project Updated.csv")
q1_2022_peer_exp <- read.csv("April-2022-Quarterly-and-Annual-Reporting-Data-through-March-31-2022 (5).xlsx - Projects.csv")
q2_2022_peer_exp <- read.csv("July-2022-Quarterly-Reporting-Data-through-June-30-2022 (5).xlsx - Projects.csv")


#q4 2021
#does not have completion status
q4_2021_peer_exp_filter <- q4_2021_peer_exp %>%
  transmute(
    recipient = `Recipient Name`,
    state_name = `State/Territory`, 
    year = 2021,
    quarter = "Q4",
    completion = "", 
    project = `Project Name`, 
    # "Expenditure.Category.Group",
    # "Expenditure.Category", 
    description = `Project Description`, 
    amount = `Adopted Budget`, 
    cumulative_obligations = `Total Obligations`, 
    cumulative_expenditures = `Total Expenditures`) %>% 
  mutate(across(amount:cumulative_expenditures, ~as.numeric(str_remove_all(., ","))))

####### recode column names
#q1 2022
#does not contain 'Completion.Status'
q1_2022_peer_exp_filter <- q1_2022_peer_exp %>%
  transmute(
    recipient = `Recipient.Name`,
    state_name = `State.Territory`, 
    year = 2022,
    quarter = "Q1",
    completion = NA_character_, 
    project = `Project.Name`, 
    # "Expenditure.Category.Group",
    # "Expenditure.Category", 
    description = `Project.Description`, 
    amount = `Adopted.Budget`, 
    cumulative_obligations = `Total.Cumulative.Obligations`, 
    cumulative_expenditures = `Total.Cumulative.Expenditures`) %>% 
  mutate(across(amount:cumulative_expenditures, ~as.numeric(str_remove_all(., ","))))


#q2 2022
q2_2022_peer_exp_filter <- q2_2022_peer_exp %>% 
  transmute(
    recipient = `Recipient.Name`,
    state_name = `State.Territory`, 
    year = 2022,
    quarter = "Q2",
    completion = `Completion.Status`, 
    project = `Project.Name`, 
    # "Expenditure.Category.Group",
    # "Expenditure.Category", 
    description = `Project.Description`, 
    amount = `Adopted.Budget`, 
    cumulative_obligations = `Total.Cumulative.Obligations`, 
    cumulative_expenditures = `Total.Cumulative.Expenditures`) %>% 
  mutate(across(amount:cumulative_expenditures, ~as.numeric(str_remove_all(., ","))))


#bind rows
expenditures_peer_temp <- bind_rows(
  q4_2021_peer_exp_filter, 
  q1_2022_peer_exp_filter,
  q2_2022_peer_exp_filter)

#create new column in expenditures_peer_temp with state abbreviation
expenditures_peer_temp$state_abbr <- state.abb[match(expenditures_peer_temp$state_name, state.name)]

expenditures_crosswalk_merge <- expenditures_peer_temp %>%
  left_join(expenditures_peer_crosswalk, by = c("recipient", "state_abbr")) %>%
  filter(!is.na(city_county))

#merge expenditures_crosswalk_merge with government dataframe
expenditures <- expenditures_crosswalk_merge %>%
  left_join(governments_long, by = c("city_county", "city_county_status"))

rm(q4_2021_peer_exp, q4_2021_peer_exp_filter,
   q1_2022_peer_exp, q1_2022_peer_exp_filter,
   q2_2022_peer_exp, q2_2022_peer_exp_filter,
   expenditures_crosswalk_merge, expenditures_peer_temp,
   expenditures_peer_crosswalk)
  
#expenditures %>% group_by(FIPS, city_county, paste0(year, "-", quarter)) %>% summarize(n = n()) %>% View()

```

```{r}

expenditures_filled <- expenditures %>%
  mutate(
    time_period = factor(paste0(quarter, "-", year),
        labels = c("Q4-2021", "Q1-2022", "Q2-2022"), 
         levels = c("Q4-2021", "Q1-2022", "Q2-2022"), ordered = TRUE)) %>%
  complete(time_period, nesting(FIPS, recipient, project)) %>%
  group_by(FIPS, recipient, project) %>%
  fill(cumulative_expenditures, .direction = "down") %>%
  ungroup()

expenditure_graph <- expenditures_filled  %>%
  group_by(FIPS, time_period) %>%
  summarize(n=sum(cumulative_expenditures, na.rm = TRUE))

ggplot(expenditure_graph, aes(x=time_period, y=n, group=FIPS)) +
  geom_line() +
  geom_point()

# t <- expenditures %>%
#   mutate(
#     time_period = factor(paste0(quarter, "-", year),
#         labels = c("Q4-2021", "Q1-2022", "Q2-2022"), 
#          levels = c("Q4-2021", "Q1-2022", "Q2-2022"), ordered = TRUE)) %>%
#   filter(FIPS == 26081) %>%
#   arrange(recipient, project, time_period)

```

```{r}
load("app/data_export.RData")

```

```{r}
save(FIPS_df, FIPS_info, governments_long, governments_wide, projects, expenditures, expenditures_lou, usa, counties, file = "app/data_export2.RData")

```

